subjects = ["C++","Python" ,"C", "Java","JavaScript"]

print(subjects)

print(subjects[0])
print(subjects[2:])
print(subjects[-1])
print("Python" in subjects)
print("Swift" in subjects)
print("Swift" not in subjects)
print("Python" not in subjects)
print(subjects+["Swift", 233])
print(subjects*3)
print(len(subjects))
subjects.append("TOC")
print(subjects)
subjects.insert(2,"OS")
print(subjects)
subjects.remove("OS")
print(subjects)
subjects.sort()
print(subjects)
subjects.reverse()
print(subjects)
subjects.pop()
print(subjects)
subjects2=subjects.copy()
print(subjects2)
subjects2.clear()
print(subjects2)
 
